-- =====================================================
-- INSERTAR JOB_VACANCIES - VERSION CORREGIDA
-- =====================================================

INSERT INTO "job_vacancies" (id, title, description, company, location, job_type, modality, salary_range, requirements, apply_type, external_url, is_active, category, created_at, updated_at)
VALUES
  (uuid_generate_v4()::text, 'Desarrollador Full Stack', 'Buscamos desarrollador con experiencia en React y Node.js', 'TechCorp', 'Asunción, Paraguay', 'junior', 'hibrido', 'Gs. 5.000.000 - 8.000.000', ARRAY['React', 'Node.js', '2+ años experiencia'], 'externo', 'https://techcorp.com/jobs/1', true, 'Tecnología', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (uuid_generate_v4()::text, 'Diseñador UX/UI', 'Diseñador creativo para productos digitales', 'Design Studio', 'Remoto', 'medio', 'remoto', 'Gs. 6.000.000 - 10.000.000', ARRAY['Figma', 'Adobe XD', 'Portfolio'], 'externo', 'https://designstudio.com/jobs/2', true, 'Diseño', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (uuid_generate_v4()::text, 'Analista de Datos', 'Análisis y visualización de datos', 'Data Analytics Co', 'Ciudad del Este, Paraguay', 'junior', 'presencial', 'Gs. 4.500.000 - 7.000.000', ARRAY['SQL', 'Python', 'Power BI'], 'externo', 'https://dataanalytics.com/jobs/3', true, 'Tecnología', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (uuid_generate_v4()::text, 'Desarrollador Frontend React', 'Desarrollo de interfaces modernas', 'Software Factory', 'Remoto', 'senior', 'remoto', 'Gs. 8.000.000 - 12.000.000', ARRAY['React', 'TypeScript', '5+ años'], 'externo', 'https://softwarefactory.com/jobs/4', true, 'Tecnología', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (uuid_generate_v4()::text, 'Especialista en Marketing Digital', 'Gestión de campañas digitales', 'Marketing Hub', 'Asunción, Paraguay', 'medio', 'hibrido', 'Gs. 5.500.000 - 9.000.000', ARRAY['Google Ads', 'Meta Ads', 'Analytics'], 'externo', 'https://marketinghub.com/jobs/5', true, 'Marketing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (uuid_generate_v4()::text, 'DevOps Engineer', 'Automatización y CI/CD', 'Cloud Services SA', 'Remoto', 'senior', 'remoto', 'Gs. 9.000.000 - 15.000.000', ARRAY['AWS', 'Docker', 'Kubernetes'], 'externo', 'https://cloudservices.com/jobs/6', true, 'Tecnología', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (uuid_generate_v4()::text, 'Desarrollador Backend Python', 'APIs y microservicios', 'Tech Solutions PY', 'Asunción, Paraguay', 'medio', 'presencial', 'Gs. 7.000.000 - 11.000.000', ARRAY['Python', 'Django', 'PostgreSQL'], 'externo', 'https://techsolutions.com/jobs/7', true, 'Tecnología', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (uuid_generate_v4()::text, 'Community Manager', 'Gestión de redes sociales', 'Digital Marketing Pro', 'Remoto', 'junior', 'remoto', 'Gs. 3.500.000 - 5.500.000', ARRAY['Redes Sociales', 'Canva', 'Copywriting'], 'externo', 'https://digitalmarketing.com/jobs/8', true, 'Marketing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (uuid_generate_v4()::text, 'QA Tester Automation', 'Testing automatizado', 'Innovate Labs', 'Ciudad del Este, Paraguay', 'medio', 'hibrido', 'Gs. 6.000.000 - 9.500.000', ARRAY['Selenium', 'Cypress', 'Testing'], 'externo', 'https://innovatelabs.com/jobs/9', true, 'Tecnología', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (uuid_generate_v4()::text, 'Product Manager', 'Gestión de productos digitales', 'StartUp Hub', 'Remoto', 'senior', 'remoto', 'Gs. 10.000.000 - 16.000.000', ARRAY['Product Management', 'Agile', 'Roadmapping'], 'externo', 'https://startuphub.com/jobs/10', true, 'Gestión', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (uuid_generate_v4()::text, 'Desarrollador Mobile Flutter', 'Apps iOS y Android', 'App Factory', 'Asunción, Paraguay', 'medio', 'hibrido', 'Gs. 6.500.000 - 10.000.000', ARRAY['Flutter', 'Dart', 'Firebase'], 'externo', 'https://appfactory.com/jobs/11', true, 'Tecnología', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (uuid_generate_v4()::text, 'Scrum Master', 'Facilitador de metodologías ágiles', 'Consulting Group', 'Remoto', 'senior', 'remoto', 'Gs. 8.500.000 - 13.000.000', ARRAY['Scrum', 'Agile', 'Certificación CSM'], 'externo', 'https://consultinggroup.com/jobs/12', true, 'Gestión', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (uuid_generate_v4()::text, 'Data Scientist', 'Machine Learning y análisis predictivo', 'AI Research Center', 'Remoto', 'senior', 'remoto', 'Gs. 11.000.000 - 18.000.000', ARRAY['Python', 'TensorFlow', 'ML'], 'externo', 'https://airesearch.com/jobs/13', true, 'Tecnología', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (uuid_generate_v4()::text, 'Diseñador Gráfico', 'Diseño visual y branding', 'Creative Agency', 'Asunción, Paraguay', 'junior', 'presencial', 'Gs. 4.000.000 - 6.500.000', ARRAY['Photoshop', 'Illustrator', 'Portfolio'], 'externo', 'https://creativeagency.com/jobs/14', true, 'Diseño', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (uuid_generate_v4()::text, 'Arquitecto de Software', 'Diseño de arquitectura de sistemas', 'Enterprise Solutions', 'Remoto', 'senior', 'remoto', 'Gs. 12.000.000 - 20.000.000', ARRAY['Microservicios', 'Cloud', '10+ años'], 'externo', 'https://enterprisesolutions.com/jobs/15', true, 'Tecnología', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (id) DO NOTHING;

-- Verificar
SELECT COUNT(*) as total_job_vacancies FROM job_vacancies WHERE is_active = true;
